# Ways to Evaluate Sklearn model

In [1]:
# standerd imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.metrics import accuracy_score
from sklearn.linear_model import Ridge
from sklearn.svm import LinearSVC
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import cross_val_score
import pickle as pc
%matplotlib inline

# 3 Ways to Evaluate
+ Estimator Score Methods
+ The Scoring parameter
+ Problem specific metric function

In [2]:
np.random.seed(1)
heart_d = pd.read_csv('heart.csv')
# data split
X = heart_d.drop('output', axis = 1)
y = heart_d['output']
# tes_train
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=.2)
cll = RandomForestClassifier().fit(X_train, y_train)
cll.score(X_test, y_test)
cll

RandomForestClassifier()

In [3]:
cll.score(X_test, y_test)*100

78.68852459016394

In [4]:
# lets apply on reggression problem
np.random.seed(4)
df_b = pd.read_csv('housing.csv')
X = df_b.drop('target', axis = 1)
y = df_b['target']
# tes_train
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=.2)
bos_m = RandomForestRegressor().fit(X_train, y_train)
bos_m.score(X_test, y_test)
# bos_m


0.8130380078489517

In [5]:
bos_m.score(X_test, y_test)

0.8130380078489517

In [6]:
np.random.seed(4)
heart_d = pd.read_csv('heart.csv')
# data split
X = heart_d.drop('output', axis = 1)
y = heart_d['output']
# tes_train
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=.2)
heart_model = RandomForestClassifier().fit(X_train, y_train)
heart_model.score(X_test, y_test)

0.8852459016393442

In [7]:
from sklearn.model_selection import cross_val_score
cross_val = cross_val_score(heart_model,X,y,cv =5)
cross_val

array([0.78688525, 0.8852459 , 0.80327869, 0.8       , 0.78333333])

In [8]:
np.mean(cross_val_score(heart_model,X,y,cv =5))

np.float64(0.8183060109289617)

In [9]:
cross_val_score(heart_model,X,y,cv =5)

array([0.81967213, 0.86885246, 0.78688525, 0.78333333, 0.75      ])

# Classification Model Evaluation accuracy of model

In [10]:
# Accuracy
# Aread Under the Curve
# confusion Matrix
# Classifiaction report


## Accuracy

In [11]:
from sklearn.model_selection import cross_val_score
np.random.seed(4)
heart_d = pd.read_csv('heart.csv')
# data split
X = heart_d.drop('output', axis = 1)
y = heart_d['output']
# tes_train
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=.2)
heart_model = RandomForestClassifier().fit(X_train, y_train)
heart_model.score(X_test, y_test)

0.8852459016393442

In [13]:
cross_val_score(heart_model,X,y,cv =5), np.mean(cross_val_score(heart_model,X,y,cv =5))

(array([0.81967213, 0.8852459 , 0.80327869, 0.8       , 0.78333333]),
 np.float64(0.8017486338797812))

In [21]:
print(f'heart disease Vaidation accuracy {np.mean(cross_val_score(heart_model,X,y,cv =5))*100:.2f}%')

heart disease Vaidation accuracy 81.83%


## Area Under the Curve

In [27]:
# recievcer operating characteristics Curve
from sklearn.metrics import roc_curve
heart_model.fit(X_train, y_train)
y_proba = heart_model.predict_proba(X_test)[:5]
# {resent
y_proba[:5], y_test[:5]

(array([[0.55, 0.45],
        [0.63, 0.37],
        [0.12, 0.88],
        [0.02, 0.98],
        [0.68, 0.32]]),
 113    1
 249    0
 18     1
 142    1
 299    0
 Name: output, dtype: int64)