# Exercise for Numpy

In [1]:
import numpy as np
import pandas as pd
import random as rd
# import matplotlib.pyplot as plt
# import seaborn as sns
# import sklearn as sk

In [2]:
# sale = mon, tue, wed, thur, fri,
# Item_1, Item_2, Item_3
# sale  = TOTAL SALES
np.random.seed(seed = True)
item_amount = np.random.randint(20, size = (5,3))
item_amount

array([[ 5, 11, 12],
       [ 8,  9, 11],
       [ 5, 15,  0],
       [16,  1, 12],
       [ 7, 13,  6]])

In [3]:
item_price = np.array([12,8,11])

In [4]:
item_price_df = pd.DataFrame(item_price.reshape(1,3),
                             index =['Item_Price'],
                             columns = ['item_1','item_2','item_3'])

In [28]:
item_price_df

item_1  item_2  item_3
Item_Price      12       8      11

In [26]:
total_price1 = item_price.dot(item_amount.T)
total_price1

array([280, 289, 180, 332, 254])

In [29]:
total_price = pd.DataFrame(total_price1.T, columns = ["Total_Price"], index = ["Mon", 'Tue', 'Wed', 'Thur', 'Fri'])
total_price

Total_Price
Mon           280
Tue           289
Wed           180
Thur          332
Fri           254

In [30]:
weekly_sales = pd.DataFrame(item_amount, columns = ["Item_1", 'Item_2', 'Item_3'], index = ["Mon", 'Tue', 'Wed', 'Thur', 'Fri'])

In [31]:
weekly_sales

Item_1  Item_2  Item_3
Mon        5      11      12
Tue        8       9      11
Wed        5      15       0
Thur      16       1      12
Fri        7      13       6

In [49]:
weekly_sales['Total_Price'] = total_price

In [50]:
weekly_sales

Item_1  Item_2  Item_3  Total_Price
Mon        5      11      12          280
Tue        8       9      11          289
Wed        5      15       0          180
Thur      16       1      12          332
Fri        7      13       6          254

In [47]:
del weekly_sales[weekly_sales.columns[3]]

In [48]:
weekly_sales

Item_1  Item_2  Item_3
Mon        5      11      12
Tue        8       9      11
Wed        5      15       0
Thur      16       1      12
Fri        7      13       6

# Comparison Operator

In [59]:
np.random.seed(seed = True)
n3d = np.random.randint(15,size = (3,4))
type(n3d)
n3d
n2d = np.random.randint(15,size = (3,4))
type(n2d)
n2d

array([[13, 12,  6,  9],
       [ 2,  4, 14,  5],
       [ 2,  4, 11, 12]])

In [60]:
n2d>n3d

array([[ True,  True, False,  True],
       [False, False,  True,  True],
       [ True,  True, False,  True]])

In [61]:
n3d>n2d

array([[False, False,  True, False],
       [ True,  True, False, False],
       [False, False,  True, False]])

In [62]:
n3d!=n2d

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [63]:
n3d>=n2d

array([[False, False,  True, False],
       [ True,  True, False, False],
       [False, False,  True, False]])

# Sorting Arrays

In [64]:
n3d

array([[ 5, 11, 12,  8],
       [ 9, 11,  5,  0],
       [ 0,  1, 12,  7]])

In [65]:
np.sort(n3d)

array([[ 5,  8, 11, 12],
       [ 0,  5,  9, 11],
       [ 0,  1,  7, 12]])

In [73]:
np.sort(n2d, axis=1)

array([[ 6,  9, 12, 13],
       [ 2,  4,  5, 14],
       [ 2,  4, 11, 12]])

In [74]:
n2d

array([[13, 12,  6,  9],
       [ 2,  4, 14,  5],
       [ 2,  4, 11, 12]])

In [76]:
# index position not the values for number
np.argsort(n2d)

array([[2, 3, 1, 0],
       [0, 1, 3, 2],
       [0, 1, 2, 3]])

In [79]:
np.argmin(n2d, axis = 0)

array([1, 1, 0, 1])

In [83]:
np.argmax(n2d, axis = 0) # axis = 0 => columns, axis = 1 => rows

array([0, 0, 1, 2])

# Reading Images