In [1]:
import numpy as np
import pandas as pd
import random as rd
# import matplotlib.pyplot as plt
# import seaborn as sns
# import sklearn as sk

# Numpy
## Most used functions
## Data Types
## Creating and viewing arrays 
## manipulating arrays

In [2]:
# Array 
n1d = np.array([1,2,3])
type(n1d)
n1d

array([1, 2, 3])

In [3]:
n2d = np.array([[1,2,3,4,5],[6,7,8,9,0]])
type(n2d)
n2d

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [4]:
n3d = np.array([[[1,2.3,3,4],[1,2,3,4],[1,2,3,4]],[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
type(n3d)
n3d

array([[[1. , 2.3, 3. , 4. ],
        [1. , 2. , 3. , 4. ],
        [1. , 2. , 3. , 4. ]],

       [[1. , 2. , 3. , 4. ],
        [1. , 2. , 3. , 4. ],
        [1. , 2. , 3. , 4. ]]])

In [5]:
# 1D aarray is called as Vector
# 2D array us called as Matrix
# 3D arrays is called as 

In [6]:
print(n1d.shape)
print(n2d.shape)
print(n3d.shape)
print(n3d.dtype)

(3,)
(2, 5)
(2, 3, 4)
float64


In [7]:
print(n1d.ndim)
print(n2d.ndim)
print(n3d.ndim)

1
2
3


In [8]:
df = pd.DataFrame(n2d)
df

0  1  2  3  4
0  1  2  3  4  5
1  6  7  8  9  0

In [9]:
#c reating array
# ones
ones = np.ones((3,3))
# Zero
zeros = np.zeros((3,4))
# random
rand = np.arange(0,10,2)

In [10]:
dff = np.random.randint(0,10, size = (3,4))
dff

array([[2, 2, 4, 1],
       [7, 2, 1, 2],
       [0, 7, 4, 4]])

In [11]:
# random seed, fix entries
np.random.seed(seed = 0)

In [12]:
npa = np.random.rand(3,5) # auto range 0 - 1
npa

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ],
       [0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152],
       [0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606]])

In [13]:
# random seed
npa.sum()

np.float64(9.042960048565472)

In [14]:
n3d

array([[[1. , 2.3, 3. , 4. ],
        [1. , 2. , 3. , 4. ],
        [1. , 2. , 3. , 4. ]],

       [[1. , 2. , 3. , 4. ],
        [1. , 2. , 3. , 4. ],
        [1. , 2. , 3. , 4. ]]])

In [15]:
n3d[:2,:1,:4] # 3d arrays [sets,row,columns]

array([[[1. , 2.3, 3. , 4. ]],

       [[1. , 2. , 3. , 4. ]]])

In [16]:
np_a = np.random.randint(10,size=(2,3,3,4)) # [dimensions, rows,columns]
np_a[:1,:1,:4,:4] # sets, furtherarray, rows, columns

array([[[[9, 4, 3, 0],
         [3, 5, 0, 2],
         [3, 8, 1, 3]]]])

# Manipulation

In [17]:
# array manipulation
n1d


array([1, 2, 3])

In [18]:
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
# add array into array 1D to 2D
n1d+ones
# how they are maps , it uses broadcasting, not by loops

array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])

In [20]:
n2d[:2,:4]*n3d[:2,:2]

array([[[ 1. ,  4.6,  9. , 16. ],
        [ 6. , 14. , 24. , 36. ]],

       [[ 1. ,  4. ,  9. , 16. ],
        [ 6. , 14. , 24. , 36. ]]])

In [21]:
n1d**2

array([1, 4, 9])

In [22]:
n2d[:2,:4]//n3d[:2,:2]

array([[[1., 0., 1., 1.],
        [6., 3., 2., 2.]],

       [[1., 1., 1., 1.],
        [6., 3., 2., 2.]]])

In [23]:
np.square(n2d)
n2d%1

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

# Aggregation

In [24]:
print(sum(n1d))

6


In [25]:
l_array = np.random.random(10000)
l_array

array([0.01357164, 0.6228461 , 0.67365963, ..., 0.27720631, 0.92986366,
       0.87019482])

In [26]:
%timeit sum(l_array)
%timeit np.sum(l_array)

687 μs ± 16.1 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
5.24 μs ± 373 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [27]:
np.max(n1d)

np.int64(3)

In [28]:
np.min(n2d)

np.int64(0)

# Statistical

In [29]:
# Mean
# + average of values
print(np.mean(n1d))
# variance
print(np.var(n1d))
# std
print(np.sqrt(np.var(n1d)))
print(np.std(n1d))

2.0
0.6666666666666666
0.816496580927726
0.816496580927726


# Matrix product Cross and Dot

In [30]:
np.random.seed(seed = True)
mat_1 = np.random.randint(10, size= (4,3))
mat_2 = np.random.randint(10, size= (4,3))

In [31]:
mat_1

array([[5, 8, 9],
       [5, 0, 0],
       [1, 7, 6],
       [9, 2, 4]])

In [32]:
mat_2

array([[5, 2, 4],
       [2, 4, 7],
       [7, 9, 1],
       [7, 0, 6]])

In [33]:
# Element wise multiplication
mat_1*mat_2

array([[25, 16, 36],
       [10,  0,  0],
       [ 7, 63,  6],
       [63,  0, 24]])

In [34]:
# Dot product, Why Dot product
# Should have same dimensions
# multiplication is like columns of the first matrixx == to Rows of 2nd Column
mat_1.dot(mat_2.T)

array([[ 77, 105, 116,  89],
       [ 25,  10,  35,  35],
       [ 43,  72,  76,  43],
       [ 65,  54,  85,  87]])

In [35]:
np.random.seed(seed=True)
ma_2 = np.random.randint(20,size=(4,3))
ma_3 = np.random.randint(21,size=(4,3))

In [36]:
ma_2

array([[ 5, 11, 12],
       [ 8,  9, 11],
       [ 5, 15,  0],
       [16,  1, 12]])

In [41]:
ma_3.T

array([[ 7, 18, 18, 10],
       [13, 20, 20, 14],
       [ 6,  5, 11, 18]])

In [38]:
ma_2*ma_3

array([[ 35, 143,  72],
       [144, 180,  55],
       [ 90, 300,   0],
       [160,  14, 216]])

In [40]:
ma_2.dot(ma_3.T)

array([[250, 370, 442, 420],
       [239, 379, 445, 404],
       [230, 390, 390, 260],
       [197, 368, 440, 390]])

In [42]:
ma_2.shape, ma_3.T.shape

((4, 3), (3, 4))