In [1]:
import numpy as np
import pandas as pd
import random as rd
# import matplotlib.pyplot as plt
# import seaborn as sns
# import sklearn as sk

# Numpy
## Most used functions
## Data Types
## Creating and viewing arrays 
## manipulating arrays

In [2]:
# Array 
n1d = np.array([1,2,3])
type(n1d)
n1d

array([1, 2, 3])

In [3]:
n2d = np.array([[1,2,3,4,5],[6,7,8,9,0]])
type(n2d)
n2d

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [4]:
n3d = np.array([[[1,2.3,3,4],[1,2,3,4],[1,2,3,4]],[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
type(n3d)
n3d

array([[[1. , 2.3, 3. , 4. ],
        [1. , 2. , 3. , 4. ],
        [1. , 2. , 3. , 4. ]],

       [[1. , 2. , 3. , 4. ],
        [1. , 2. , 3. , 4. ],
        [1. , 2. , 3. , 4. ]]])

In [5]:
# 1D aarray is called as Vector
# 2D array us called as Matrix
# 3D arrays is called as 

In [6]:
print(n1d.shape)
print(n2d.shape)
print(n3d.shape)
print(n3d.dtype)

(3,)
(2, 5)
(2, 3, 4)
float64


In [7]:
print(n1d.ndim)
print(n2d.ndim)
print(n3d.ndim)

1
2
3


In [8]:
df = pd.DataFrame(n2d)
df

0  1  2  3  4
0  1  2  3  4  5
1  6  7  8  9  0

In [9]:
#c reating array
# ones
np.ones((3,3))
# Zero
np.zeros((3,4))
# random
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [10]:
dff = np.random.randint(0,10, size = (3,4))
dff

array([[4, 4, 7, 4],
       [5, 7, 1, 8],
       [2, 9, 1, 3]])

In [11]:
# random seed, fix entries
np.random.seed(seed = 0)

In [12]:
npa = np.random.rand(3,5) # auto range 0 - 1
npa

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ],
       [0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152],
       [0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606]])

In [13]:
# random seed
npa.sum()

np.float64(9.042960048565472)

In [14]:
n3d

array([[[1. , 2.3, 3. , 4. ],
        [1. , 2. , 3. , 4. ],
        [1. , 2. , 3. , 4. ]],

       [[1. , 2. , 3. , 4. ],
        [1. , 2. , 3. , 4. ],
        [1. , 2. , 3. , 4. ]]])

In [26]:
n3d[:2,:1,:4] # 3d arrays [sets,row,columns]

array([[[1. , 2.3, 3. , 4. ]],

       [[1. , 2. , 3. , 4. ]]])