In [1]:
import numpy as np
# import pandas as pd
# import matplotlib.pyplot as plt
# import seaborn as sns
# import sklearn as sk

# Numpy
## Most used functions
## Data Types
## Creating and viewing arrays 
## manipulating arrays

In [2]:
# Array 
n1d = np.array([1,2,3])
type(n1d)
n1d

array([1, 2, 3])

In [3]:
n2d = np.array([[1,2,3,4,5],[6,7,8,9,0]])
type(n2d)
n2d

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [4]:
n3d = np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]],[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
type(n3d)
n3d

array([[[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]]])

In [5]:
# 1D aarray is called as Vector
# 2D array us called as Matrix
# 3D arrays is called as 

In [6]:
print(n1d.shape)
print(n2d.shape)
print(n3d.shape)

(3,)
(2, 5)
(2, 3, 4)


In [7]:
print(n1d.ndim)
print(n2d.ndim)
print(n3d.ndim)

1
2
3
